### ISSUE TITLE
도와주세요..

### ISSUE THREAD

**Issue by entry62045** [EntryHack/FollowBot#1]
저도 팔로우봇 작동시키려고 리포지토리를 Fork 누르고 헤로쿠 가서 Deploy 눌렀는데 오류납니다.
제 팔로우봇 계정으로 설정하는 거랑 헤로쿠로 작동시킬 때 설정하는 거랑 깃허브 파일에 비밀번호 넣지 않고 헤로쿠에서 중요한 내용(비밀번호, 토큰 등)을 변수로 했을 때 어떤 변수 값 설정하는 그런 거 있는데 그거 어떻게 설정하는지 알려주시면 감사하겠습니다.

**Comment by dn1t** [comment]
환경변수를 사용하세요. 저도 헤로쿠 안써서 모르고, 그런건 검색하면 바로 나옵니다.
